title: EstraPy2
description: Documentation for the XANESE/EXAFS analysis tool EstraPy
theme: just-the-docs

url: https://ramsteak.github.io/EstraPy2/

aux_links:
  GitHub: https://github.com/ramsteak/EstraPy2

color_scheme: dark

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
